### ISSUE TITLE
作者可以建一个 Flutter 埋点群吗

### ISSUE THREAD

**Issue by GvcZhang** [SBDavid/flutter_page_tracker#10]
RT，最近公司也在做 Flutter 无痕埋点，希望作者能够建一个群，让各位有志之士能够在一起研究，共同进步，最终克服 Flutter 全埋点方面所有问题，真正做到开源，同时建立这方面的领导地位和影响力。

**Comment by SBDavid** [comment]
微信群吗？没想到埋点也可以建个群😂， 我建一个试试，看有没有来
<img width="379" alt="image" src="https://user-images.githubusercontent.com/13783101/87390423-6880c280-c5db-11ea-8206-1d0abcd632cb.png">

**Comment by koalababy2024** [comment]
@SBDavid @GvcZhang 二维码过期了，加我，13616108739

**Comment by GvcZhang** [comment]
我在上面的群里了

**Comment by koalababy2024** [comment]
@GvcZhang 拉我进去啊，我的微信号再上面

**Comment by kxr224** [comment]
@SBDavid  大佬，二维码过期了，能不能再发一个。
