### ISSUE TITLE
如何获取页面信息

### ISSUE THREAD

**Issue by GvcZhang** [SBDavid/flutter_page_tracker#11]
比如通过路由跳转到了 B 页面，那么如何在didpush里面获取 B 页面的信息呢，例如B页面的类名等

**Comment by SBDavid** [comment]
每个页面都可以获取到自己Route对象。你是问这个吗？

**Comment by GvcZhang** [comment]
通过 Route 对象拿不到跳转的页面吧，比如 MaterialApp 的 routes 里有是这样的：
```java
 routes: {
          "/buttonPage": (BuildContext context) => ButtonTestPage(),
          "/dialogPage": (BuildContext context) => DialogTestPage(),
          "/tabBarPage": (BuildContext context) => TabBarTestPage(),
}
```
然后通过`Navigator.of(context).pushNamed('/buttonPage');`，在 didPush 里如何获取 ButtonTestPage 的信息呢？

**Comment by SBDavid** [comment]
是Observe里的didPush吗？Route对象有RouteSettings，里面有name。问的是这个？
