### ISSUE TITLE
有个疑问，为什么需要重写didPush didPop等方法？

### ISSUE THREAD

**Issue by koalababy2024** [SBDavid/flutter_page_tracker#7]
维持一个页面栈，直接在initState()和dispose()中，对这个栈进行操作；为什么还需要在didPush 和 didPop中操作这个栈，求教。

**Comment by SBDavid** [comment]
didPush和didPop可以统一写在Observer里，还有Observer里有remove、replace等等方法。以后还能继续拓展呀。
