### ISSUE TITLE
PopUtil的问题

### ISSUE THREAD

**Issue by koalababy2024** [SBDavid/flutter_page_tracker#8]
A页面push到B页面，B页面push到C页面，然后C页面直接pop到A页面，按照目前您这个框架，B页面的didPageView()和didPageExit()都会调用，实际上按照产品的定义，从C页面直接pop到A页面，B页面的两个的didPageView()和didPageExit()是不需要埋点的，怎么解决这个问题？

C页面pop到A页面的方法如下：
```
              Navigator.of(context).popUntil((Route route){
                  if (route.settings.name == "/"){
                    return true;
                  }

                  return false;
              });
```

**Comment by SBDavid** [comment]
还没有试过这种，不过至少不会触发B页面的didPageView() 吧
